name: Twitter Follow Tracker

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs once a week
  workflow_dispatch:  # Allows manual runs

jobs:
  track-followers:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: pip install tweepy

    - name: Run tracker script
      env:
        TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
      run: python tracker.py
